name: test

on:
  pull_request:
  push:
  schedule:
    - cron: '00 21 * * *'

jobs:
  test:
    runs-on: ubuntu-latest
    # let's use syslog-ng dev teams build env for shortcutting
    container:
      image: ghcr.io/syslog-ng/dbld-devshell:latest

    steps:
      - name: Checkout syslog-ng source
        uses: actions/checkout@v2

      - name: obtain syslog-ng - clone source
        run: |
          git clone https://github.com/syslog-ng/syslog-ng.git

      - name: obtain syslog-ng - compile & install
        run: |
          cd syslog-ng
          mkdir build && cd build
          cmake -DCMAKE_INSTALL_PREFIX=/tmp/install ..
          make -j $(nproc) install

      - name: test pi config
        run: |
          /tmp/install/sbin/syslog-ng -F -f pi.conf > output.txt &
          sleep 5
          /tmp/install/sbin/syslog-ng-ctl stop

          set -e
          wc -l output.txt | grep 99
          grep -c '3141592901' output.txt 

      - name: test zero cost condition
        run: |
          /tmp/install/sbin/syslog-ng -F -f zero-cost-condition.conf > output.txt &
          sleep 5
          /tmp/install/sbin/syslog-ng-ctl stop

          set -e
          grep -c 'parse-A' output.txt 

      - name: test tic-tac-toe
        run: |
          /tmp/install/sbin/syslog-ng -F -f tic-tac-toe.conf > output.txt &
          sleep 5
          /tmp/install/sbin/syslog-ng-ctl stop

          set -e
          grep -c 'You are with O, please provide a step' output.txt 
       
       
